name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment to use
        required: true
        type: string
      url:
        description: Deployment URL to display to users
        required: false
        type: string
      noop:
        description: Run deployment in dry run mode
        type: boolean
        required: false
        default: false

jobs:
  deploy:
    name: Wrangler
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    concurrency: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack before running setup-node
        run: corepack enable
      - name: Setup Node ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'yarn'
      - name: Ensure corepack is used
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Get Wrangler version from package.json
        id: wrangler-version
        run: |
          version=$(cat package.json | jq -r .devDependencies.wrangler | sed -E 's/^[\^~><=][=]?//')
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Deploy with Wrangler${{ inputs.noop && ' (dry run)' || '' }}
        uses: cloudflare/wrangler-action@v3
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy${{ inputs.noop && ' --dry-run' || '' }}
          environment: ${{ !inputs.noop && inputs.environment || '' }}
          secrets: |
            JWT_SECRET
          wranglerVersion: ${{ steps.wrangler-version.outputs.version }}
