name: Deploy

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment in which to deploy the changes
        type: choice
        required: true
        options:
          - staging
          - production

jobs:
  deploy-dryrun:
    name: Dry Run
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: build
      noop: true
  deploy-staging:
    name: Staging
    if: (github.event_name == 'push' && github.event.ref == 'refs/heads/develop') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'staging')
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: staging
      url: plantguard-api.dalbitresb.com
  deploy-prod:
    name: Production
    if: (github.event_name == 'push' && github.event.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'production')
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
      url: plantguard-api-staging.dalbitresb.com
